export const INBOX = 'Inbox';
export const SPAM = 'Spam';
export const DELETED_ITEMS = 'Deleted Items';
export const CUSTOM_FOLDER = 'Custom Folder';

export const GET_INBOX_MESSAGES = 'GET_INBOX_MESSAGES';
export const INBOX_RECEIVED = 'INBOX_RECEIVED';
export const UPDATE_MESSAGE = 'UPDATE_MESSAGE';

export const GET_SPAM_MESSAGES = 'GET_SPAM_MESSAGES';
export const SPAM_RECEIVED = 'SPAM_RECEIVED';

export const GET_CUSTOM_MESSAGES = 'GET_CUSTOM_MESSAGES';
export const CUSTOM_RECEIVED = 'CUSTOM_RECEIVED';

export const GET_DELETED_MESSAGES = 'GET_DELETED_MESSAGES';
export const DELETED_RECEIVED = 'DELETED_RECEIVED';

export const FLAG_MESSAGE = 'FLAG_MESSAGE';
export const DELETE_MESSAGE = 'DELETE_MESSAGE';
export const UNREAD_MESSAGE = 'UNREAD_MESSAGE';
export const GET_INBOX_FLAGGED_MESSAGES = 'GET_INBOX_FLAGGED_MESSAGES';

export const FLAGGED_INBOX_RECEIVED = 'FLAGGED_INBOX_RECEIVED';